print("Este es un archivo nuevo")
print("Este es un archivo nuevo")
print("Este es un archivo nuevo")
print("Este es un archivo nuevo")
print("Este es un archivo nuevo")
print("Este es un archivo nuevo")
print("Esta es una nueva linea")
